const drinks = ["Mango Green Tea",
    "Grapefruit Green Tea",
    "Honey Lemon",
    "Wintermelon with Lemon Juice",
    "Strawberry Black Tea",
    "Pineapple Green / Black Tea",
    "Hawaii Fruit Tea",
    "Kiwi Fruit Tea",
    "Mango & Passion Fruit Green Tea",
    "Whole Lemon Black Tea / Green Tea",
    "Passion Fruit, Orange & Grapefruit Tea",
    "Classic Black Tea",
    "Classic Green Tea",
    "Classic Oolong Tea",
    "Wintermelon Tea",
    "Honey Black / Green Tea",
    "Ginger Tea",
    "Black Creama Tea",
    "Green Creama Tea",
    "Oolong Creama Tea",
    "Wintermelon Tea Creama",
    "Coffee Creama",
    "Cocoa Creama",
    "Mango Green Tea Creama",
    "Matcha Green Tea Creama",
    "Fresh Milk Tea",
    "Wintermelon with Fresh Milk",
    "Cocoa Lover",
    "Boba Fresh Milk",
    "Matcha with Fresh Milk",
    "Classic Milk Tea",
    "Honey Milk Tea",
    "Classic Coffee",
    "Ginger Milk Tea",
    "Ice Cream Green Tea",
    "Coffee Milk Tea",
    "Hokkaido Pearl Milk Tea ( Caramel Toffee )",
    "Okinawa Pearl Milk Tea ( Roasted Brown Sugar )",
    "Taro Pearl Milk Tea",
    "Mango Green Milk Tea",
    "QQ Happy Family Milk Tea",
    "Matcha Red Bean Milk Tea",
    "Oreo Ice Blended",
    "Taro Ice Blended",
    "Milk Tea Ice Blended",
    "Matcha Red Bean",
    "Coffee Ice Blended",
    "Mango Ice Blended",
    "Strawberry Ice Blended"]

    const toppings = [
        "boba",
        "mini boba",
        "pudding",
        "aloe vera",
        "red bean",
        "aiyu jelly",
        "herb jelly",
        "lychee jelly",
        "ice cream"
    ]

